title: example.com
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/grace_emoji.png"

# Social Links
email: gracekim30820@gmail.com
github_username: eunhyekim-grace
twitter_username:
instagram_username: ffgrace_
linkedin_username: grace-eunhye-kim
facebook_username:

# External API
giscus_repo: "eunhyekim-grace/eunhyekim-grace.github.io"
giscus_repoId: "R_kgDOLvuC7Q"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOLvuC7c4Cew5v"
goatcounter_code: gracegithubblog
google_analytics:

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
